### PR TITLE
OH HAI I BUMPED THIS FOR U

### PR DESCRIPTION
**Pull request by passy**
Will you come visit me now to bump back? 

[Review on Reviewable](https://reviewable.io/reviews/sindresorhus/devtools-detect/21)

### CODE REVIEW

**Comment by gdi2290** [comment]
+1

**Comment by AdriVanHoudt** [comment]
:shipit:

**Comment by stephenplusplus** [comment]
```diff
-43.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446091.1
+43.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679823480865132823066470938446091.1
```

**Comment by samccone** [comment]
LGTM

**Comment by sindresorhus** [comment]
deal-with-it

**Comment by samccone** [comment]
What a jerk

**Comment by resynth1943** [comment]
oml that activity above by Sindre :eyes:

**Comment by stephenplusplus** [comment]
We were so young.

**Comment by samccone** [comment]
We were so naive.

**Comment by resynth1943** [comment]
We were so dumb.

**Pull request closed without merging**
