### PR TITLE
added orientation detection

### PR DESCRIPTION
**Pull request by a-axton**
I needed this for a project and thought I'd share

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? Sorry I don't get the purpose of this. Would you mind elaborating? :)

**Comment by a-axton** [comment]
It's for layout based changes. DevTools takes up a lot screen space and depending on which orientation can make the page look completely different. In hindsight, using a combination of media queries would probably work too

**Comment by sindresorhus** [comment]
I'm missing the context here. What kind of orientation are we talking about? Device orientation? How are you using this? I'm still having a hard time understanding the purpose of this.

**Comment by a-axton** [comment]
Sorry, I was referring to the orientation of the DevTools window (horizontal/vertical). My use case is for an in-browser tool to be used during development. Certain elements in my layout are anchored to the side/bottom of the page. If DevTools is open vertically, the viewport width is now limited, so I need to adjust my ui to account for that. Likewise for when DevTools is open horizontally, the viewport height is now limited so I need to change the ui.

**Comment by sindresorhus** [comment]
Thanks for sharing :) :beers:

**Pull request merged**
